### ISSUE TITLE
CREDENTIALS file example?

### ISSUE THREAD

**Issue by tapatianbeast** [gaoyunzhi/telegram_twitter_subscription_bot#3]
CREDENTIALS file example?

**Comment by gaoyunzhi** [comment]
{
	"bot_token": "YOUR_TOKEN"
	"twitter_consumer_key": "YOUR_TOKEN"
	"twitter_consumer_secret": "YOUR_TOKEN"
	"twitter_access_token": "YOUR_TOKEN"
	"twitter_access_secret": "YOUR_TOKEN"
	"telegraph": "YOUR_TOKEN_CAN_BE_EMPTY"
}

**Comment by tapatianbeast** [comment]
Traceback (most recent call last):
  File "twitter_subscription_bot.py", line 22, in <module>
    CREDENTIALS = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 2 (char 70)

**Comment by gaoyunzhi** [comment]
Add ',' at the end for all except the last item please. :)
